---
- name: Create directory for containerfile
  file:
    path: "{{ managed_containerfiles_path }}/ansible-podman-minimal"
    state: directory

- name: Create Containerfile from template
  template:
    src: Containerfile.j2
    dest: "{{ managed_containerfiles_path }}/ansible-podman-minimal/Containerfile"

- name: Build Podman container using system package podman but without using podman python bindings
  command:
    cmd: podman build -t ansible-podman-minimal {{ managed_containerfiles_path }}/ansible-podman-minimal

- name: Create a container running Podman using system package podman but without using podman python bindings
  command:
    cmd: podman run -d --name ansible-podman-minimal -v {{ ansible_env.HOME }}:/root ansible-podman-minimal
