---
- include_role:
    name: buildah_dict

- debug:
    var: buildah_dict[container_name]
  when: buildah_dict is defined

- name: Create new Buildah container if it doesn't exist
  command: buildah from --name {{ container_name }} docker.io/archlinux:latest
  register: newcontainer
  become: true
  when: buildah_dict[container_name] is not defined
  delegate_to: localhost

- name: Ensure Python 3 is installed
  command: buildah run {{ container_name }} -- pacman -Syu --noconfirm python
  become: true
  delegate_to: localhost

- name: Ensure sudo is installed
  command: buildah run {{ container_name }} -- pacman -Syu --noconfirm sudo
  become: true
  delegate_to: localhost

- name: Check environment
  command: buildah run {{ container_name }} -- env
  become: true
  delegate_to: localhost